---
- name: Install shell completions
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: fpath+=$HOME/.config/hcloud/completion/zsh
    insertbefore: ^# End OMZ_CONFIG block
  listen:
    - shell configuration replaced
    - application completion installed

- name: Export hcloud token
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "export HCLOUD_TOKEN={{ hcloud_token }}"
    insertbefore: ^# End ENV block
  listen:
    - shell configuration replaced
    - commandline program installed
