---
- name: Install openjdk packages
  community.general.homebrew:
    name:
      - openjdk@11
      - openjdk@17
      - openjdk
  notify:
    - commandline programm installed
    - openjdk package installed
