---
cifs_credentials_path: /etc/cifs_credentials
cifs_mountpoint: /mnt
cifs_system_uid: root
cifs_system_gid: root
cifs_share: backup
cifs_mount_options:
  - iocharset=utf8
  - rw
  - credentials={{ cifs_credentials_path }}
  - uid={{ cifs_system_uid }}
  - gid={{ cifs_system_gid }}
  - file_mode=0660
  - dir_mode=0770
  - rsize=65536
  - wsize=130048
