---
storagebox_cifs_credentials_path: /etc/cifs_credentials
storagebox_cifs_mountpoint: /mnt
storagebox_cifs_system_uid: root
storagebox_cifs_system_gid: root
storagebox_cifs_share: backup
storagebox_cifs_mount_options:
  - iocharset=utf8
  - rw
  - credentials={{ storagebox_cifs_credentials_path }}
  - uid={{ storagebox_cifs_system_uid }}
  - gid={{ storagebox_cifs_system_gid }}
  - file_mode=0660
  - dir_mode=0770
  - rsize=65536
  - wsize=130048
