---
- name: Render legacy marker
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "{{ item.marker }}"
    insertbefore: "{{ item.placement }}"
  loop:
    - { marker: "# ENV_LEGACY marker", placement: "# Begin ENV block" }
    - { marker: "# PATH_LEGACY marker", placement: "# Begin PATH block" }
    - { marker: "# OMZ_PREF_LEGACY marker", placement: "# Begin OMZ_PREF block" }
    - { marker: "# PLUGINS_LEGACY marker", placement: "# Begin PLUGINS block" }
    - { marker: "# OMZ_CONFIG_LEGACY marker", placement: "# End OMZ_CONFIG block" }
    - { marker: "# USER_CONFIG_LEGACY marker", placement: "# Begin USER_CONFIG block" }

- name: Render environment configuration
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "{{ lookup('ansible.builtin.file', 'legacy/environment_postbegin') }}"
    insertafter: ^# ENV_LEGACY marker

- name: Render path configuration
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "{{ lookup('ansible.builtin.file', 'legacy/path_postbegin') }}"
    insertafter: ^# PATH_LEGACY marker

- name: Render preferences
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "{{ lookup('ansible.builtin.file', 'legacy/omz_config_postbegin') }}"
    insertafter: ^# OMZ_PREF_LEGACY marker

- name: Render plugins
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "{{ lookup('ansible.builtin.file', 'legacy/omz_plugins_postbegin') }}"
    insertafter: ^# PLUGINS_LEGACY marker

- name: Render configuration
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "{{ lookup('ansible.builtin.file', 'legacy/omz_config_preend') }}"
    insertbefore: ^# OMZ_CONFIG_LEGACY marker

- name: Render user configuration
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "{{ lookup('ansible.builtin.file', 'legacy/user_config_postbegin') }}"
    insertafter: ^# USER_CONFIG_LEGACY marker
