---
- name: Log reset of .zshrc
  ansible.builtin.debug:
    msg: |
      oh-my-zsh configuration resetted.
      You may need to rerun other roles and playbooks to restore custom configuration.
  listen:
    - shell configuration replaced

- name: Apply legacy configuration tasks
  ansible.builtin.include_tasks:
    file: legacy.yml
    apply:
      tags: always
  tags: legacy
  listen:
    - shell configuration replaced

- name: Configure zsh site functions plugin
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: fpath+=$(brew --prefix)/share/zsh/site-functions
    insertbefore: ^# End OMZ_CONFIG block
  listen:
    - shell configuration replaced

- name: Import ssh-agent shell configuration
  ansible.builtin.include_tasks:
    file: ssh-agent.yml
    apply:
      tags: always
  listen:
    - shell configuration replaced
