---
- name: Provide local software and configuration
  hosts: localhost
  connection: local

  pre_tasks:

    - name: Require host OS to be macOS
      ansible.builtin.import_tasks: tasks/macos-guard.yml
      tags: always

    - name: Update Homebrew and upgrade all packages
      tags: update
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
        upgrade_options: ignore-pinned
      when: not ansible_check_mode
      notify:
        - hombrew packages upgraded

    - name: Upgrade all Homebrew casks
      community.general.homebrew_cask:
        upgrade_all: true
      when: not ansible_check_mode
      changed_when: false

  roles:

    - oh-my-zsh
    - hcloud
    - iterm2
    - openjdk
    - maven
    - zoxide
